"""Initial migration

Revision ID: 001
Revises:
Create Date: 2026-01-02 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hikvision_id', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('synced_to_device', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hikvision_id'), 'users', ['hikvision_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('work_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_shifts_id'), 'work_shifts', ['id'], unique=False)
    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('terminal_ip', sa.String(length=45), nullable=True),
    sa.Column('employee_no', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('card_no', sa.String(length=50), nullable=True),
    sa.Column('card_reader_id', sa.String(length=50), nullable=True),
    sa.Column('event_type_code', sa.String(length=50), nullable=True),
    sa.Column('event_type_description', sa.String(length=255), nullable=True),
    sa.Column('remote_host_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_employee_no'), 'attendance_events', ['employee_no'], unique=False)
    op.create_index(op.f('ix_attendance_events_id'), 'attendance_events', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_events_terminal_ip'), 'attendance_events', ['terminal_ip'], unique=False)
    op.create_index(op.f('ix_attendance_events_timestamp'), 'attendance_events', ['timestamp'], unique=False)
    op.create_table('system_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_users_email'), 'system_users', ['email'], unique=True)
    op.create_index(op.f('ix_system_users_id'), 'system_users', ['id'], unique=False)
    op.create_index(op.f('ix_system_users_username'), 'system_users', ['username'], unique=True)
    op.create_table('user_device_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_device_sync_device_id'), 'user_device_sync', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_device_sync_id'), 'user_device_sync', ['id'], unique=False)
    op.create_index(op.f('ix_user_device_sync_sync_status'), 'user_device_sync', ['sync_status'], unique=False)
    op.create_index(op.f('ix_user_device_sync_user_id'), 'user_device_sync', ['user_id'], unique=False)
    op.create_table('user_shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['work_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_shift_assignments_id'), 'user_shift_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_user_shift_assignments_shift_id'), 'user_shift_assignments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_user_shift_assignments_user_id'), 'user_shift_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_shift_assignments_user_id'), table_name='user_shift_assignments')
    op.drop_index(op.f('ix_user_shift_assignments_shift_id'), table_name='user_shift_assignments')
    op.drop_index(op.f('ix_user_shift_assignments_id'), table_name='user_shift_assignments')
    op.drop_table('user_shift_assignments')
    op.drop_index(op.f('ix_user_device_sync_user_id'), table_name='user_device_sync')
    op.drop_index(op.f('ix_user_device_sync_sync_status'), table_name='user_device_sync')
    op.drop_index(op.f('ix_user_device_sync_id'), table_name='user_device_sync')
    op.drop_index(op.f('ix_user_device_sync_device_id'), table_name='user_device_sync')
    op.drop_table('user_device_sync')
    op.drop_index(op.f('ix_system_users_username'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_id'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_email'), table_name='system_users')
    op.drop_table('system_users')
    op.drop_index(op.f('ix_attendance_events_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_terminal_ip'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_employee_no'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_work_shifts_id'), table_name='work_shifts')
    op.drop_table('work_shifts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hikvision_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
